// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/routing-api/authentication"
)

type FakeUaaKeyFetcher struct {
	FetchKeyStub        func() (string, error)
	fetchKeyMutex       sync.RWMutex
	fetchKeyArgsForCall []struct{}
	fetchKeyReturns struct {
		result1 string
		result2 error
	}
}

func (fake *FakeUaaKeyFetcher) FetchKey() (string, error) {
	fake.fetchKeyMutex.Lock()
	fake.fetchKeyArgsForCall = append(fake.fetchKeyArgsForCall, struct{}{})
	fake.fetchKeyMutex.Unlock()
	if fake.FetchKeyStub != nil {
		return fake.FetchKeyStub()
	} else {
		return fake.fetchKeyReturns.result1, fake.fetchKeyReturns.result2
	}
}

func (fake *FakeUaaKeyFetcher) FetchKeyCallCount() int {
	fake.fetchKeyMutex.RLock()
	defer fake.fetchKeyMutex.RUnlock()
	return len(fake.fetchKeyArgsForCall)
}

func (fake *FakeUaaKeyFetcher) FetchKeyReturns(result1 string, result2 error) {
	fake.FetchKeyStub = nil
	fake.fetchKeyReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

var _ authentication.UaaKeyFetcher = new(FakeUaaKeyFetcher)
