// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"code.cloudfoundry.org/gorouter/route"
)

type FakeEndpointIterator struct {
	NextStub        func() *route.Endpoint
	nextMutex       sync.RWMutex
	nextArgsForCall []struct{}
	nextReturns     struct {
		result1 *route.Endpoint
	}
	EndpointFailedStub        func()
	endpointFailedMutex       sync.RWMutex
	endpointFailedArgsForCall []struct{}
	PreRequestStub            func(e *route.Endpoint)
	preRequestMutex           sync.RWMutex
	preRequestArgsForCall     []struct {
		e *route.Endpoint
	}
	PostRequestStub        func(e *route.Endpoint)
	postRequestMutex       sync.RWMutex
	postRequestArgsForCall []struct {
		e *route.Endpoint
	}
}

func (fake *FakeEndpointIterator) Next() *route.Endpoint {
	fake.nextMutex.Lock()
	fake.nextArgsForCall = append(fake.nextArgsForCall, struct{}{})
	fake.nextMutex.Unlock()
	if fake.NextStub != nil {
		return fake.NextStub()
	} else {
		return fake.nextReturns.result1
	}
}

func (fake *FakeEndpointIterator) NextCallCount() int {
	fake.nextMutex.RLock()
	defer fake.nextMutex.RUnlock()
	return len(fake.nextArgsForCall)
}

func (fake *FakeEndpointIterator) NextReturns(result1 *route.Endpoint) {
	fake.NextStub = nil
	fake.nextReturns = struct {
		result1 *route.Endpoint
	}{result1}
}

func (fake *FakeEndpointIterator) EndpointFailed() {
	fake.endpointFailedMutex.Lock()
	fake.endpointFailedArgsForCall = append(fake.endpointFailedArgsForCall, struct{}{})
	fake.endpointFailedMutex.Unlock()
	if fake.EndpointFailedStub != nil {
		fake.EndpointFailedStub()
	}
}

func (fake *FakeEndpointIterator) EndpointFailedCallCount() int {
	fake.endpointFailedMutex.RLock()
	defer fake.endpointFailedMutex.RUnlock()
	return len(fake.endpointFailedArgsForCall)
}

func (fake *FakeEndpointIterator) PreRequest(e *route.Endpoint) {
	fake.preRequestMutex.Lock()
	fake.preRequestArgsForCall = append(fake.preRequestArgsForCall, struct {
		e *route.Endpoint
	}{e})
	fake.preRequestMutex.Unlock()
	if fake.PreRequestStub != nil {
		fake.PreRequestStub(e)
	}
}

func (fake *FakeEndpointIterator) PreRequestCallCount() int {
	fake.preRequestMutex.RLock()
	defer fake.preRequestMutex.RUnlock()
	return len(fake.preRequestArgsForCall)
}

func (fake *FakeEndpointIterator) PreRequestArgsForCall(i int) *route.Endpoint {
	fake.preRequestMutex.RLock()
	defer fake.preRequestMutex.RUnlock()
	return fake.preRequestArgsForCall[i].e
}

func (fake *FakeEndpointIterator) PostRequest(e *route.Endpoint) {
	fake.postRequestMutex.Lock()
	fake.postRequestArgsForCall = append(fake.postRequestArgsForCall, struct {
		e *route.Endpoint
	}{e})
	fake.postRequestMutex.Unlock()
	if fake.PostRequestStub != nil {
		fake.PostRequestStub(e)
	}
}

func (fake *FakeEndpointIterator) PostRequestCallCount() int {
	fake.postRequestMutex.RLock()
	defer fake.postRequestMutex.RUnlock()
	return len(fake.postRequestArgsForCall)
}

func (fake *FakeEndpointIterator) PostRequestArgsForCall(i int) *route.Endpoint {
	fake.postRequestMutex.RLock()
	defer fake.postRequestMutex.RUnlock()
	return fake.postRequestArgsForCall[i].e
}

var _ route.EndpointIterator = new(FakeEndpointIterator)
