// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/cloudfoundry/gorouter/route_fetcher"
)

type FakeRouteFetcherInterface struct {
	FetchRoutesStub        func() error
	fetchRoutesMutex       sync.RWMutex
	fetchRoutesArgsForCall []struct{}
	fetchRoutesReturns     struct {
		result1 error
	}
}

func (fake *FakeRouteFetcherInterface) FetchRoutes() error {
	fake.fetchRoutesMutex.Lock()
	fake.fetchRoutesArgsForCall = append(fake.fetchRoutesArgsForCall, struct{}{})
	fake.fetchRoutesMutex.Unlock()
	if fake.FetchRoutesStub != nil {
		return fake.FetchRoutesStub()
	} else {
		return fake.fetchRoutesReturns.result1
	}
}

func (fake *FakeRouteFetcherInterface) FetchRoutesCallCount() int {
	fake.fetchRoutesMutex.RLock()
	defer fake.fetchRoutesMutex.RUnlock()
	return len(fake.fetchRoutesArgsForCall)
}

func (fake *FakeRouteFetcherInterface) FetchRoutesReturns(result1 error) {
	fake.FetchRoutesStub = nil
	fake.fetchRoutesReturns = struct {
		result1 error
	}{result1}
}

var _ route_fetcher.RouteFetcherInterface = new(FakeRouteFetcherInterface)
