// Code generated by protoc-gen-gogo.
// source: heartbeatrequest.proto
// DO NOT EDIT!

package control

import proto "code.google.com/p/gogoprotobuf/proto"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = math.Inf

// / A HeartbeatRequest command elicits a heartbeat from a component or app
type HeartbeatRequest struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *HeartbeatRequest) Reset()         { *m = HeartbeatRequest{} }
func (m *HeartbeatRequest) String() string { return proto.CompactTextString(m) }
func (*HeartbeatRequest) ProtoMessage()    {}

func init() {
}
