#!/bin/bash

set -e -x -u

function printStatus {
      if [ $? -eq 0 ]; then
          echo -e "\nSWEET SUITE SUCCESS"
      else
          echo -e "\nSUITE FAILURE"
      fi
  }

trap printStatus EXIT

. $(dirname $0)/gorequired

. $(dirname $0)/godep-env

#Install ginkgo from Godeps into Godeps workspace
go install -v github.com/onsi/ginkgo/ginkgo

#Run all tests
ginkgo -r -failOnPending -keepGoing -randomizeAllSpecs -skipMeasurements=true -race "$@"
