// This file was generated by counterfeiter
package fakes

import (
	"sync"

	"github.com/cloudfoundry-incubator/uaa-go-client"
	"github.com/cloudfoundry-incubator/uaa-go-client/schema"
)

type FakeClient struct {
	FetchTokenStub        func(forceUpdate bool) (schema.Token, error)
	fetchTokenMutex       sync.RWMutex
	fetchTokenArgsForCall []struct {
		forceUpdate bool
	}
	fetchTokenReturns struct {
		result1 schema.Token
		result2 error
	}
	FetchKeyStub        func() (string, error)
	fetchKeyMutex       sync.RWMutex
	fetchKeyArgsForCall []struct{}
	fetchKeyReturns     struct {
		result1 string
		result2 error
	}
	DecodeTokenStub        func(uaaToken string, desiredPermissions ...string) error
	decodeTokenMutex       sync.RWMutex
	decodeTokenArgsForCall []struct {
		uaaToken           string
		desiredPermissions []string
	}
	decodeTokenReturns struct {
		result1 error
	}
}

func (fake *FakeClient) FetchToken(forceUpdate bool) (schema.Token, error) {
	fake.fetchTokenMutex.Lock()
	fake.fetchTokenArgsForCall = append(fake.fetchTokenArgsForCall, struct {
		forceUpdate bool
	}{forceUpdate})
	fake.fetchTokenMutex.Unlock()
	if fake.FetchTokenStub != nil {
		return fake.FetchTokenStub(forceUpdate)
	} else {
		return fake.fetchTokenReturns.result1, fake.fetchTokenReturns.result2
	}
}

func (fake *FakeClient) FetchTokenCallCount() int {
	fake.fetchTokenMutex.RLock()
	defer fake.fetchTokenMutex.RUnlock()
	return len(fake.fetchTokenArgsForCall)
}

func (fake *FakeClient) FetchTokenArgsForCall(i int) bool {
	fake.fetchTokenMutex.RLock()
	defer fake.fetchTokenMutex.RUnlock()
	return fake.fetchTokenArgsForCall[i].forceUpdate
}

func (fake *FakeClient) FetchTokenReturns(result1 schema.Token, result2 error) {
	fake.FetchTokenStub = nil
	fake.fetchTokenReturns = struct {
		result1 schema.Token
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) FetchKey() (string, error) {
	fake.fetchKeyMutex.Lock()
	fake.fetchKeyArgsForCall = append(fake.fetchKeyArgsForCall, struct{}{})
	fake.fetchKeyMutex.Unlock()
	if fake.FetchKeyStub != nil {
		return fake.FetchKeyStub()
	} else {
		return fake.fetchKeyReturns.result1, fake.fetchKeyReturns.result2
	}
}

func (fake *FakeClient) FetchKeyCallCount() int {
	fake.fetchKeyMutex.RLock()
	defer fake.fetchKeyMutex.RUnlock()
	return len(fake.fetchKeyArgsForCall)
}

func (fake *FakeClient) FetchKeyReturns(result1 string, result2 error) {
	fake.FetchKeyStub = nil
	fake.fetchKeyReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) DecodeToken(uaaToken string, desiredPermissions ...string) error {
	fake.decodeTokenMutex.Lock()
	fake.decodeTokenArgsForCall = append(fake.decodeTokenArgsForCall, struct {
		uaaToken           string
		desiredPermissions []string
	}{uaaToken, desiredPermissions})
	fake.decodeTokenMutex.Unlock()
	if fake.DecodeTokenStub != nil {
		return fake.DecodeTokenStub(uaaToken, desiredPermissions...)
	} else {
		return fake.decodeTokenReturns.result1
	}
}

func (fake *FakeClient) DecodeTokenCallCount() int {
	fake.decodeTokenMutex.RLock()
	defer fake.decodeTokenMutex.RUnlock()
	return len(fake.decodeTokenArgsForCall)
}

func (fake *FakeClient) DecodeTokenArgsForCall(i int) (string, []string) {
	fake.decodeTokenMutex.RLock()
	defer fake.decodeTokenMutex.RUnlock()
	return fake.decodeTokenArgsForCall[i].uaaToken, fake.decodeTokenArgsForCall[i].desiredPermissions
}

func (fake *FakeClient) DecodeTokenReturns(result1 error) {
	fake.DecodeTokenStub = nil
	fake.decodeTokenReturns = struct {
		result1 error
	}{result1}
}

var _ uaa_go_client.Client = new(FakeClient)
