#!/bin/bash

set -e -x -u

function printStatus {
      if [ $? -eq 0 ]; then
          echo -e "\nSWEET SUITE SUCCESS"
      else
          echo -e "\nSUITE FAILURE"
      fi
  }

trap printStatus EXIT

. $(dirname $0)/gorequired

#Download & Install gnatsd into GOPATH (or use pre-installed version)
go get -v github.com/apcera/gnatsd

. $(dirname $0)/godep-env

#Install ginkgo from Godeps into Godeps workspace
go install -v github.com/onsi/ginkgo/ginkgo

echo -e "\n Formatting packages..."
go fmt ./...

echo -e "\n Installing packages for Vetting them..."
for package in $(find {access_log,common,config,metrics,proxy,registry,route} -type d)
do
    export install_file="github.com/cloudfoundry/gorouter/$package"
    go install $install_file
done

for file in $(find {access_log,common,config,metrics,proxy,registry,route} \( -name "*.go" -not -iname "*test.go" \))
do
    go tool vet -v -all -shadow=true $file
done

#Run all tests -keepGoing
ginkgo -r -failOnPending -randomizeAllSpecs -skipMeasurements=true -race "$@"

