#!/bin/bash

set -e -x

go get -v github.com/apcera/gnatsd

export GOPATH=$PWD/Godeps/_workspace:$GOPATH

FIRST_GOPATH=`echo $GOPATH | cut -d':' -f1`

mkdir -p $FIRST_GOPATH/bin
export PATH=$FIRST_GOPATH/bin:$PATH

go test -v ./... "$@"

echo "PASSED"
